import Head from 'next/head'
import LandingPage from '../components/landingPage'
import LandingAnimation from '../components/landingAnimation'
import Footer from '../components/footer'
import styles from '../styles/Home.module.css'
import { useState } from 'react'
import { AnimatePresence } from 'framer-motion'




function Home() {
  // set loading to false if you want to skeep the loading phase.
  const [loading, setLoading] = useState(false);


  return (
    <div className={styles.container}>
      <Head key="1">
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main className={styles.main}>
        <AnimatePresence>
          {loading ? <LandingAnimation setLoading={setLoading} /> : <LandingPage />}
        </AnimatePresence>
      </main>

      <footer className={styles.footer}>
        <Footer/>
      </footer>
    </div>
  )
}


export default Home

